### ISSUE TITLE
Building on Windows

### ISSUE THREAD

**Issue by mattbradbury** [Leo1003/rust-osshkeys#1]
It's not always straightforward how to get openssl on Windows machines.  If you could expose the "vendored" feature from the openssl crate, that would be awesome!

**Comment by Leo1003** [comment]
I forgot that rust-openssl has this feature. With this feature, I can also enable the unit test on Windows. 
Thanks for reminding.

**Comment by Leo1003** [comment]
Now, it should be able to compile with `openssl-vendored` feature on Windows.
However, because of the problem the underlying PEM library.
When parsing CRLF line endings PEM files, it will report parsing error.
The library seems inactively and I am not a fan of `nom`. I will seek to another library or develop one by myself.

**Comment by Leo1003** [comment]
I think this can be closed now.
